### ISSUE TITLE
What does this repo do? :p

### ISSUE THREAD

**Issue by lifeoflikhon** [sefatanam/nx-workspace-enterprise#1]

**Comment by sefatanam** [comment]
This repo is followed by [Production-Grade Angular Tutorial](https://frontendmasters.com/courses/production-angular/nx-workspaces-angular-cli/)  😎 & I'm trying to be KOOL 😁 @lifeoflikhon vai

**Comment by sefatanam** [comment]
Don't forget the password 😎
